import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const tournaments = [
  // Southeast
  {
    name: 'PG Southeast Summer Classic',
    organizer: 'PERFECT_GAME' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['12U', '13U', '14U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-06-20'),
    endDate: new Date('2026-06-22'),
    registrationDeadline: new Date('2026-06-10'),
    locationName: 'Chastain Park Athletic Complex',
    address: '600 Chastain Park Ave NW',
    city: 'Atlanta',
    state: 'GA',
    zip: '30342',
    lat: 33.8892,
    lng: -84.3902,
    entryFee: 695,
    maxTeams: 32,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1001',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1001',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  {
    name: 'Triple Crown Peach State Invitational',
    organizer: 'TRIPLE_CROWN' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['10U', '11U', '12U'],
    format: 'DOUBLE_ELIM' as const,
    startDate: new Date('2026-07-11'),
    endDate: new Date('2026-07-13'),
    registrationDeadline: new Date('2026-06-28'),
    locationName: 'Suwanee Sports Academy',
    address: '2415 Main St W',
    city: 'Suwanee',
    state: 'GA',
    zip: '30024',
    lat: 34.0515,
    lng: -84.0702,
    entryFee: 550,
    maxTeams: 24,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.triplecrownsp​orts.com/tournaments/peach-state-2026',
    sourceUrl: 'https://www.triplecrownsp​orts.com/tournaments/peach-state-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  // Texas
  {
    name: 'PG Texas Summer Championships',
    organizer: 'PERFECT_GAME' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['13U', '14U', '15U', '16U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-07-18'),
    endDate: new Date('2026-07-20'),
    registrationDeadline: new Date('2026-07-05'),
    locationName: 'Grand Park Sports Complex',
    address: '2500 E Southlake Blvd',
    city: 'Southlake',
    state: 'TX',
    zip: '76092',
    lat: 32.9420,
    lng: -97.1310,
    entryFee: 750,
    maxTeams: 48,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1002',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1002',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  {
    name: 'Triple Crown Texas Bash',
    organizer: 'TRIPLE_CROWN' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['9U', '10U', '11U', '12U'],
    format: 'DOUBLE_ELIM' as const,
    startDate: new Date('2026-06-27'),
    endDate: new Date('2026-06-29'),
    registrationDeadline: new Date('2026-06-13'),
    locationName: 'Round Rock Sports Center',
    address: '3400 E Palm Valley Blvd',
    city: 'Round Rock',
    state: 'TX',
    zip: '78665',
    lat: 30.5083,
    lng: -97.6789,
    entryFee: 495,
    maxTeams: 32,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.triplecrownsp​orts.com/tournaments/texas-bash-2026',
    sourceUrl: 'https://www.triplecrownsp​orts.com/tournaments/texas-bash-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  // Florida
  {
    name: 'USSSA Florida Elite Summer Showcase',
    organizer: 'USSSA' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['10U', '12U', '14U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-06-13'),
    endDate: new Date('2026-06-15'),
    registrationDeadline: new Date('2026-06-01'),
    locationName: 'Osceola Heritage Park',
    address: '1875 Silver Spur Lane',
    city: 'Kissimmee',
    state: 'FL',
    zip: '34744',
    lat: 28.3209,
    lng: -81.3959,
    entryFee: 625,
    maxTeams: 40,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.usssa.com/baseball/events/florida-elite-2026',
    sourceUrl: 'https://www.usssa.com/baseball/events/florida-elite-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  {
    name: 'PG Florida World Series Qualifier',
    organizer: 'PERFECT_GAME' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['15U', '16U', '17U', '18U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-07-25'),
    endDate: new Date('2026-07-27'),
    registrationDeadline: new Date('2026-07-12'),
    locationName: 'Lee County Sports Complex',
    address: '14100 Six Mile Cypress Pkwy',
    city: 'Fort Myers',
    state: 'FL',
    zip: '33912',
    lat: 26.5379,
    lng: -81.8585,
    entryFee: 795,
    maxTeams: 32,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1003',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1003',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  // Midwest
  {
    name: 'Triple Crown Midwest Championships',
    organizer: 'TRIPLE_CROWN' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['11U', '12U', '13U', '14U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-07-04'),
    endDate: new Date('2026-07-06'),
    registrationDeadline: new Date('2026-06-20'),
    locationName: 'Ozzie Smith Sports Complex',
    address: '1489 Ozzie Smith Dr',
    city: 'Chesterfield',
    state: 'MO',
    zip: '63017',
    lat: 38.6631,
    lng: -90.5771,
    entryFee: 525,
    maxTeams: 32,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.triplecrownsp​orts.com/tournaments/midwest-2026',
    sourceUrl: 'https://www.triplecrownsp​orts.com/tournaments/midwest-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  {
    name: 'PG Great Lakes Summer Invitational',
    organizer: 'PERFECT_GAME' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['12U', '13U', '14U', '15U'],
    format: 'DOUBLE_ELIM' as const,
    startDate: new Date('2026-08-01'),
    endDate: new Date('2026-08-03'),
    registrationDeadline: new Date('2026-07-18'),
    locationName: 'Impact Field Sports Complex',
    address: '8900 Waukegan Rd',
    city: 'Morton Grove',
    state: 'IL',
    zip: '60053',
    lat: 42.0452,
    lng: -87.7826,
    entryFee: 650,
    maxTeams: 32,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1004',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1004',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  // Northeast
  {
    name: 'USA Baseball Northeast Regional Qualifier',
    organizer: 'USA_BASEBALL' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['12U', '15U', '18U'],
    format: 'ROUND_ROBIN' as const,
    startDate: new Date('2026-07-18'),
    endDate: new Date('2026-07-20'),
    registrationDeadline: new Date('2026-07-01'),
    locationName: 'McCoy Stadium Complex',
    address: '1 Columbus Ave',
    city: 'Pawtucket',
    state: 'RI',
    zip: '02860',
    lat: 41.8748,
    lng: -71.3811,
    entryFee: 400,
    maxTeams: 16,
    surface: 'GRASS' as const,
    registrationUrl: 'https://web.usabaseball.com/events/northeast-regional-2026',
    sourceUrl: 'https://web.usabaseball.com/events/northeast-regional-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  {
    name: 'USSSA Northeast Summer Slam',
    organizer: 'USSSA' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['10U', '11U', '12U', '13U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-06-20'),
    endDate: new Date('2026-06-22'),
    registrationDeadline: new Date('2026-06-07'),
    locationName: 'Bucks County Turf Club',
    address: '2 Stadium Dr',
    city: 'Doylestown',
    state: 'PA',
    zip: '18901',
    lat: 40.3101,
    lng: -75.1299,
    entryFee: 575,
    maxTeams: 32,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.usssa.com/baseball/events/northeast-slam-2026',
    sourceUrl: 'https://www.usssa.com/baseball/events/northeast-slam-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'OPEN' as const,
  },
  // West / California
  {
    name: 'PG West Coast Summer Showcase',
    organizer: 'PERFECT_GAME' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['14U', '15U', '16U', '17U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-07-11'),
    endDate: new Date('2026-07-13'),
    registrationDeadline: new Date('2026-06-28'),
    locationName: 'Dedeaux Field Complex',
    address: '3400 S Hoover St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90089',
    lat: 34.0183,
    lng: -118.2851,
    entryFee: 725,
    maxTeams: 32,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1005',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1005',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  {
    name: 'Triple Crown Desert Classic',
    organizer: 'TRIPLE_CROWN' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['9U', '10U', '11U', '12U', '13U'],
    format: 'DOUBLE_ELIM' as const,
    startDate: new Date('2026-06-06'),
    endDate: new Date('2026-06-08'),
    registrationDeadline: new Date('2026-05-24'),
    locationName: 'Surprise Stadium Complex',
    address: '15960 N Bullard Ave',
    city: 'Surprise',
    state: 'AZ',
    zip: '85374',
    lat: 33.6296,
    lng: -112.3679,
    entryFee: 495,
    maxTeams: 40,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.triplecrownsp​orts.com/tournaments/desert-classic-2026',
    sourceUrl: 'https://www.triplecrownsp​orts.com/tournaments/desert-classic-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  // Softball
  {
    name: 'PG Softball Summer Nationals',
    organizer: 'PERFECT_GAME' as const,
    sport: 'SOFTBALL' as const,
    ageDivisions: ['12U', '14U', '16U', '18U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-07-25'),
    endDate: new Date('2026-07-27'),
    registrationDeadline: new Date('2026-07-10'),
    locationName: 'USA Softball Hall of Fame Complex',
    address: '2801 NE 50th St',
    city: 'Oklahoma City',
    state: 'OK',
    zip: '73111',
    lat: 35.4920,
    lng: -97.4869,
    entryFee: 595,
    maxTeams: 48,
    surface: 'TURF' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=2001',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=2001',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  // Colorado
  {
    name: 'Triple Crown Colorado Mountain Classic',
    organizer: 'TRIPLE_CROWN' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['10U', '12U', '14U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-08-08'),
    endDate: new Date('2026-08-10'),
    registrationDeadline: new Date('2026-07-25'),
    locationName: 'Bandimere Speedway Sports Park',
    address: '3051 S Youngfield St',
    city: 'Lakewood',
    state: 'CO',
    zip: '80228',
    lat: 39.6706,
    lng: -105.1566,
    entryFee: 525,
    maxTeams: 32,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.triplecrownsp​orts.com/tournaments/colorado-2026',
    sourceUrl: 'https://www.triplecrownsp​orts.com/tournaments/colorado-2026',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
  // Carolinas
  {
    name: 'PG Carolina Fall Showcase',
    organizer: 'PERFECT_GAME' as const,
    sport: 'BASEBALL' as const,
    ageDivisions: ['13U', '14U', '15U', '16U'],
    format: 'POOL_BRACKET' as const,
    startDate: new Date('2026-09-19'),
    endDate: new Date('2026-09-21'),
    registrationDeadline: new Date('2026-09-05'),
    locationName: 'Cary Field Hockey & Baseball Complex',
    address: '2200 Reedy Creek Rd',
    city: 'Cary',
    state: 'NC',
    zip: '27518',
    lat: 35.7327,
    lng: -78.8052,
    entryFee: 650,
    maxTeams: 32,
    surface: 'GRASS' as const,
    registrationUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1006',
    sourceUrl: 'https://www.perfectgame.org/Tournaments/Default.aspx?event=1006',
    dataSource: 'SCRAPED' as const,
    isPublished: true,
    status: 'UPCOMING' as const,
  },
]

async function main() {
  console.log('Seeding tournaments...')

  await prisma.tournament.deleteMany({ where: { dataSource: 'SCRAPED' } })

  for (const t of tournaments) {
    await prisma.tournament.create({ data: t })
  }

  console.log(`Seeded ${tournaments.length} tournaments`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
