// Environment config with Zod validation — P8: fail fast if misconfigured
import { z } from 'zod'

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().default(3000),
  DATABASE_URL: z.string().url(),
  REDIS_URL: z.string().url(),
  // Keys injected as env vars (generated by scripts/generate-keys.sh)
  JWT_PRIVATE_KEY: z.string().min(50),
  JWT_PUBLIC_KEY: z.string().min(50),
  JWT_ACCESS_EXPIRES_IN: z.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN: z.string().default('30d'),
  COOKIE_SECRET: z.string().min(16).default('dev-secret-32-chars-change-in-prod!'),
  SENDGRID_API_KEY: z.string().optional(),
  SENDGRID_FROM_EMAIL: z.string().email().default('noreply@diamondhub.app'),
  APP_URL: z.string().url().default('http://localhost:5173'),
  CORS_ORIGINS: z.string().default('http://localhost:5173'),
  GOOGLE_CLIENT_ID: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  AWS_ACCESS_KEY_ID: z.string().optional(),
  AWS_SECRET_ACCESS_KEY: z.string().optional(),
  AWS_S3_BUCKET: z.string().default('diamondhub-uploads'),
  AWS_REGION: z.string().default('us-east-1'),
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TWILIO_FROM_NUMBER: z.string().optional(),
  FCM_SERVER_KEY: z.string().optional(),
})

// In test environment, provide dummy keys so config doesn't fail
const rawEnv =
  process.env['NODE_ENV'] === 'test'
    ? {
        ...process.env,
        DATABASE_URL: process.env['DATABASE_URL'] ?? 'postgresql://test:test@localhost:5432/test',
        REDIS_URL: process.env['REDIS_URL'] ?? 'redis://localhost:6379',
        JWT_PRIVATE_KEY: process.env['JWT_PRIVATE_KEY'] ?? '-----BEGIN PRIVATE KEY-----\ntest\n-----END PRIVATE KEY-----',
        JWT_PUBLIC_KEY: process.env['JWT_PUBLIC_KEY'] ?? '-----BEGIN PUBLIC KEY-----\ntest\n-----END PUBLIC KEY-----',
      }
    : process.env

export const config = envSchema.parse(rawEnv)
export type Config = typeof config
